// Generated by CoffeeScript 1.10.0
var clubs;

clubs = {
  atm: 78,
  ars: 57,
  rma: 86,
  liv: 64,
  fcb: 81,
  manc: 65
};

module.exports = function(robot) {
  return robot.respond(/get me result (.*)/i, function(msg) {
    var team, url;
    team = escape(msg.match[1]);
    url = 'http://api.football-data.org/alpha/teams/' + clubs[team] + '/fixtures';
    return msg.http(url).headers({
      Accept: 'application/json'
    }).get()(function(err, res, body) {
      var first, json, key, last, value;
      json = JSON.parse(body);
      first = json.fixtures;
      last = json.fixtures[0];
      for (key in first) {
        value = first[key];
        if (value.status === 'TIMED') {
          break;
        } else {
          last = value;
        }
      }
      return msg.send(last.homeTeamName + ' ' + last.result.goalsHomeTeam + ' - ' + last.result.goalsAwayTeam + ' ' + last.awayTeamName);
    });
  });
};
